theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
toolbar:
  - styleselect  undo redo | alignleft aligncenter alignright alignjustify | bold italic | bullist numlist outdent indent | forecolor backcolor | link | uploadimage | table


plugins:
  - table
  - uploadimage
  - image
  - textcolor
  - link
  - emoticons
language: 'pl'