theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
toolbar:
  - styleselect | code |  undo redo | alignleft aligncenter alignright alignjustify | bold italic | bullist numlist outdent indent | forecolor backcolor | link | uploadimage | table | code


plugins:
  - table
  - uploadimage
  - image
  - textcolor
  - link
  - emoticons
  - code

language: 'pl'
relative_urls: false


remove_script_host: false
